import json
from snowflake.snowpark.context import get_active_session


def load_prompt(filename):
    with open(filename, "r", encoding="utf-8") as f:
        return f.read()


def extract_json(text):
    text = (text or "").strip()
    decoder = json.JSONDecoder()

    for i, ch in enumerate(text):
        if ch == "{":
            try:
                obj, _ = decoder.raw_decode(text[i:])
                return obj
            except json.JSONDecodeError:
                continue

    raise ValueError(f"Aucun JSON valide trouvé dans la sortie : {text}")


def format_retrieved_context(top_k_lines, max_items=5):
    if not top_k_lines:
        return "No similar resolved tickets retrieved."

    formatted_lines = []

    for i, item in enumerate(top_k_lines[:max_items], start=1):
        if not isinstance(item, dict):
            formatted_lines.append(f"Resolved ticket example {i}:\n{str(item)}")
            continue

        subject = str(item.get("SUBJECT", "") or "").strip()
        body = str(item.get("BODY", "") or "").strip()
        answer = str(item.get("ANSWER", "") or "").strip()
        similarity = item.get("SIMILARITY", "")

        try:
            similarity = f"{float(similarity):.4f}"
        except (TypeError, ValueError):
            similarity = str(similarity)

        formatted_lines.append(
            f"""Resolved ticket example {i}:
Subject: {subject}
Customer message: {body}
Resolved answer: {answer}
Similarity score: {similarity}"""
        )

    return "\n\n".join(formatted_lines)


def generate_response(ticket_text, department, sentiment, top_k_lines, correction=None, model="llama3-8b"):
    session = get_active_session()

    print("\n========== AGENT 5 | GENERATE RESPONSE ==========")
    print("[Input] department =", department)
    print("[Input] sentiment =", sentiment)
    print("[Input] correction =", correction)
    print("[Input] top_k_lines count =", len(top_k_lines) if top_k_lines else 0)

    retrieved_context = format_retrieved_context(top_k_lines)

    prompt_template = load_prompt("prompts/response.txt")

    formatted_prompt = prompt_template.format(
        ticket_text=ticket_text,
        department=department,
        sentiment=sentiment,
        retrieved_context=retrieved_context
    )

    if correction:
        formatted_prompt += f"""

### CORRECTION FROM EVALUATION AGENT ###

The previous response generated by the system was incorrect.

Reason:
{correction}

You must regenerate a better response.

Important instructions:
- Carefully read the retrieved context.
- Make sure the response directly answers the customer's request.
- Do not repeat the previous mistake.
- Ensure the answer is clear, accurate, and helpful.
"""

    print("[Prompt preview]")
    print(formatted_prompt[:2000])

    query = f"""
        SELECT SNOWFLAKE.CORTEX.COMPLETE(
            '{model}',
            $$ {formatted_prompt} $$
        ) AS response
    """

    try:
        result = session.sql(query).collect()
        raw_output = result[0][0]
        print("[Raw model output]")
        print(raw_output)
    except Exception as e:
        print("[SNOWFLAKE COMPLETE ERROR]", e)
        raise

    try:
        parsed = extract_json(str(raw_output))
        final_response = str(parsed.get("response", "")).strip()
        print("[Parsed response]")
        print(final_response)
        print("========== END AGENT 5 ==========\n")
        return final_response
    except Exception as e:
        print("[JSON PARSING ERROR]", e)
        print("========== END AGENT 5 WITH ERROR ==========\n")
        raise