CREATE OR REPLACE TABLE PROJET_TAL.PUBLIC.TICKETS_EMBEDDED AS
SELECT
    SUBJECT,
    BODY,
    ANSWER,
    CLEAN_TEXT,
    LANGUAGE,
    QUEUE,
    TYPE,
    PRIORITY,
    TAG_1, TAG_2, TAG_3, TAG_4, TAG_5, TAG_6, TAG_7, TAG_8,
    SNOWFLAKE.CORTEX.EMBED_TEXT_1024(
        'snowflake-arctic-embed-l-v2.0',
        CLEAN_TEXT
    ) AS EMBEDDING
FROM PROJET_TAL.PUBLIC.CLEAN_TICKETS
WHERE CLEAN_TEXT IS NOT NULL AND LENGTH(CLEAN_TEXT) > 0;

